# action.yml
name: 'NGS Action'
description: 'Publish event information to an NGS subject'
branding:
  icon: 'command'
  color: 'red'
inputs:
  nats:
    description: 'NATs server'
    required: false
    default: 'connect.ngs.global'
  subject:
    description: 'NATs subject to publish on'
    required: false
    default: 'GA'
  user:
    description: 'User JWT'
    required: true
    default: ''
  seed:
    description: 'User NKEY Seed'
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
