name: Deploy Docker

on:
  release:
    types: [published]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_DEPLOY }}
      - run: echo "$GITHUB_REF"
      - run: echo "$GITHUB_REF" | cut -d '/' -f 3
      - id: tag
        run: echo "::set-ouput name=tag::latest"
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true # Will only build if this is not here
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.tag.outputs.tag }}
