name: Deploy Docker

# Run workflow on tags starting with v (eg. v2, v1.2.0)
on:
  release:
    types: [published]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_DEPLOY }}
      - id: get-tag
        run: |
          tag=$(echo ${{GITHUB_REF}} | cut -d/ -f3)
          echo "::set-output name=tag::$tag"
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true # Will only build if this is not here
          tags: |
            ghcr.io/${{ github.repository }}:${{steps.get-tag.outputs.tag}}
            ghcr.io/${{ github.repository }}:latest
